# Generated by Django 3.1 on 2022-06-19 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placementbid',
            options={'ordering': ['-placementbid_modified']},
        ),
        migrations.RemoveField(
            model_name='placement',
            name='placement_created',
        ),
        migrations.RemoveField(
            model_name='placement',
            name='placement_modified',
        ),
        migrations.AddField(
            model_name='placement',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='placement',
            name='total_pieces',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_address',
            field=models.CharField(default='SOME STRING', max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_modified',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(default='SOME STRING', max_length=255),
        ),
        migrations.AlterField(
            model_name='placement',
            name='placement_title',
            field=models.CharField(default='SOME STRING', max_length=255),
        ),
    ]
