# Generated by Django 3.1 on 2022-06-19 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220619_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bid_status',
            field=models.BooleanField(default=True),
        ),
    ]
