# Generated by Django 3.1 on 2022-06-19 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20220619_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='placement',
            name='picture',
            field=models.ImageField(default='/home/zeeshan/My-FYP/static/ap1.jpeg', upload_to='blah'),
        ),
    ]
