# Generated by Django 3.1 on 2022-06-19 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_placement_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placement',
            name='picture',
            field=models.ImageField(default='/home/zeeshan/My-FYP/static/ap1.jpeg', upload_to='static'),
        ),
    ]
